keys:
  - &admin_evlli_pgp 56B96D1C10D68F49E31BB8A18092413A3F6DD75F
  - &host_sonic age1p5s3cyjwqw0xg3rfljwq5zha36f5j0zysqqjxnqkk3zhhec0zg8szvcq4q
  - &host_cloudy age1els3ygj4gnvtg2thj0zcx4sxlkmlg68rdagjp5lpv8gzw9ealaeqy2gzwx

creation_rules:
  - path_regex: secrets/all/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *admin_evlli_pgp
        age:
          - *host_sonic
          - *host_cloudy

  - path_regex: secrets.yaml
    key_groups:
      - pgp:
          - *admin_evlli_pgp
        age:
          - *host_sonic
          - *host_cloudy

  - path_regex: secrets/hosts/sonic.yaml
    key_groups:
      - pgp:
          - *admin_evlli_pgp
        age:
          - *host_sonic

  - path_regex: secrets/hosts/cloudy.yaml
    key_groups:
      - pgp:
          - *admin_evlli_pgp
        age:
          - *host_cloudy
